// <copyright file="GlobalSuppressions.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "Skip", Scope = "namespace", Target = "~N:Ugit")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Skip", Scope = "member", Target = "~M:Ugit.DefaultDiff.DiffTrees(System.Collections.Generic.IDictionary{System.String,System.String},System.Collections.Generic.IDictionary{System.String,System.String})~System.String")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Skip", Scope = "member", Target = "~M:Ugit.Extensions.ParseArguments``17(CommandLine.Parser,System.Collections.Generic.IEnumerable{System.String})~CommandLine.ParserResult{System.Object}")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1118:Parameter should not span multiple lines", Justification = "Skip", Scope = "member", Target = "~M:Ugit.Extensions.ParseArguments``17(CommandLine.Parser,System.Collections.Generic.IEnumerable{System.String})~CommandLine.ParserResult{System.Object}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Skip", Scope = "member", Target = "~M:Ugit.Extensions.MapResult``18(CommandLine.ParserResult{System.Object},System.Func{``0,``17},System.Func{``1,``17},System.Func{``2,``17},System.Func{``3,``17},System.Func{``4,``17},System.Func{``5,``17},System.Func{``6,``17},System.Func{``7,``17},System.Func{``8,``17},System.Func{``9,``17},System.Func{``10,``17},System.Func{``11,``17},System.Func{``12,``17},System.Func{``13,``17},System.Func{``14,``17},System.Func{``15,``17},System.Func{``16,``17},System.Func{System.Collections.Generic.IEnumerable{CommandLine.Error},``17})~``17")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Skip", Scope = "member", Target = "~M:Ugit.Extensions.ParseArguments``18(CommandLine.Parser,System.Collections.Generic.IEnumerable{System.String})~CommandLine.ParserResult{System.Object}")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1118:Parameter should not span multiple lines", Justification = "Skip", Scope = "member", Target = "~M:Ugit.Extensions.ParseArguments``18(CommandLine.Parser,System.Collections.Generic.IEnumerable{System.String})~CommandLine.ParserResult{System.Object}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "skip", Scope = "member", Target = "~M:Ugit.Extensions.MapResult``19(CommandLine.ParserResult{System.Object},System.Func{``0,``18},System.Func{``1,``18},System.Func{``2,``18},System.Func{``3,``18},System.Func{``4,``18},System.Func{``5,``18},System.Func{``6,``18},System.Func{``7,``18},System.Func{``8,``18},System.Func{``9,``18},System.Func{``10,``18},System.Func{``11,``18},System.Func{``12,``18},System.Func{``13,``18},System.Func{``14,``18},System.Func{``15,``18},System.Func{``16,``18},System.Func{``17,``18},System.Func{System.Collections.Generic.IEnumerable{CommandLine.Error},``18})~``18")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "Skip", Scope = "namespace", Target = "~N:Ugit.Options")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1313:Parameter names should begin with lower-case letter", Justification = "SKip", Scope = "member", Target = "~M:Ugit.Program.Status(Ugit.Options.StatusOption)~System.Int32")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1313:Parameter names should begin with lower-case letter", Justification = "Skip", Scope = "member", Target = "~M:Ugit.Program.Init(Ugit.Options.InitOption)~System.Int32")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1312:Variable names should begin with lower-case letter", Justification = "By design", Scope = "member", Target = "~M:Ugit.Operations.DefaultCommitOperation.CreateCommit(System.String)~System.String")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "Skip", Scope = "member", Target = "~P:Ugit.DefaultDataProvider.FileSystem")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1312:Variable names should begin with lower-case letter", Justification = "By design", Scope = "member", Target = "~P:Ugit.Operations.DefaultBranchOperation.Current")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1312:Variable names should begin with lower-case letter", Justification = "By Design", Scope = "member", Target = "~M:Ugit.Operations.DefaultCheckoutOperation.Checkout(System.String)")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "By Design", Scope = "namespace", Target = "~N:Ugit.Operations")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1312:Variable names should begin with lower-case letter", Justification = "By design", Scope = "member", Target = "~M:Ugit.Operations.DefaultCommitOperation.CommitValidate()")]
