on:
  push:
    tags:
      - 'v*'

name: Publish

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup donet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          ugit-cli_name="ugit-cli-$tag-${{ matrix.target }}"
          dotnet publish src/Tindo.Ugit.CLI/Tindo.Ugit.CLI.csproj --framework net6.0 --runtime "${{ matrix.target }}" -c Release -o "$ugit-cli_name" -p:PublishSingleFile=true --self-contained true
          if [ "${{ matrix.taget }}" == "win-x64" ]; then
            7z a -tzip "${ugit-cli_name}.zip" "./${ugit-cli_name}/*"
          else  
            tar czvf "${ugit-cli_name}.tar.gz" "$ugit-cli_name"
          fi
          rm -r "$ugit-cli_name"
          ugit-server_name="ugit-server-$tag-${{ matrix.target }}"
          dotnet publish src/Tindo.Ugit.Server/Tindo.Ugit.Server.csproj --framework net6.0 --runtime "${{ matrix.target }}" -c Release -o "$ugit-server_name" -p:PublishSingleFile=true
          if [ "${{ matrix.taget }}" == "win-x64" ]; then
            7z a -tzip "${ugit-server_name}.zip" "./${ugit-server_name}/*"
          else  
            tar czvf "${ugit-server_name}.tar.gz" "$ugit-server_name"
          fi
          rm -r "$ugit-server_name"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "ugit-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}